name: CI Implementation
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: "5.0"

      - name: Run backend
        run: |
          sudo apt-get install wait-for-it -y
          wait-for-it -h localhost -p 27017 -t 10 -q -s -- echo "mongoose is running" 
          cd contact-fox-backend
          npm i
          npm start &
          wait-for-it -h localhost -p 5000 -t 10 -q -s -- echo "contact-fox-backend is running"

      - name: Run frontend
        run: |
          cd contact-fox-frontend
          npm i
          npm start &
          wait-for-it -h localhost -p 3000 -t 10 -q -s -- echo " contact-fox-frontend is running"

      - name: Run test
        run: |
          cd tests
          npm i
          npm run test:e2e ./features/login.feature
          npm run test:e2e ./features/newUserRegistration.feature
